install CommandLine Tools automatically

diff --git a/bin/macinit b/bin/macinit
--- a/bin/macinit
+++ b/bin/macinit
@@ -35,8 +35,33 @@ dirs=(
 ~/.ssh
 )
 
+# get sudo access
+echo "please input sudo password"
+sudo /usr/bin/true
+while /usr/bin/true; do
+    sleep 300
+    sudo -n /usr/bin/true
+    /bin/kill -0 "$$" 2>/dev/null || exit
+done &
+
 # install xcode commandline tools
-gcc
+# if ! [ -d "/Library/Developer/CommandLineTools" ]; then
+if ! /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables; then
+    echo "install Xcode CommandLine Tools"
+    # This file prompts that Command Line Tools should be installed
+    sudo /usr/bin/touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+    sudo /usr/sbin/softwareupdate -i $(/usr/sbin/softwareupdate -l | /usr/bin/grep -B 1 -E "Command Line (Developer|Tools)" | /usr/bin/awk -F"*" '/^ +\\*/ {print $2}' | /usr/bin/sed 's/^ *//' | /usr/bin/tail -n1)
+    sudo /bin/rm -f /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
+    sudo /usr/bin/xcode-select --switch /Library/Developer/CommandLineTools
+fi
+
+# if ! [ -d "/Library/Developer/CommandLineTools" ]; then
+if ! /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables; then
+    echo "install Xcode CommandLine Tools failed, Please install it manually"
+    sudo /usr/bin/xoode-select --install
+    exit 1
+fi
+
 # install xcode and accept license
 sudo xcodebuild -license accept
 
